import StoreLayout from "@/components/layout/Layout";
import OrderHistory from "@/components/orders/OrderHistory";
import React from "react";

const OrdersPage = () => {
    // Comprehensive dummy order data
const dummyOrders = [
  {
    id: 1,
    productName: "FEEL TRACK Solid Men Dark Blue, Grey Track Pants",
    description: "Premium quality track pants with comfortable fabric and perfect fit for casual wear",
    color: "Dark Blue, Grey",
    size: "3XL",
    quantity: 1,
    price: 443,
    originalPrice: 599,
    discount: 26,
    status: "shipped",
    deliveryInfo: "Arriving tomorrow by 11 pm",
    statusMessage: "Your item has been shipped via Express Delivery",
    orderDate: "2024-12-07",
    estimatedDelivery: "2024-12-08",
    orderNumber: "ORD-7842",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop",
    category: "Fashion",
    brand: "Urban Classics",
    rating: 4.2,
    reviews: 128,
    deliveryMethod: "Express",
    trackingNumber: "TRK78421563",
  },
  {
    id: 2,
    productName: "CROCO JAR 750 ml Glass Bottle",
    description: "Elegant glass bottle with crocodile embossed design, perfect for kitchen storage",
    color: "Clear",
    size: "750ml",
    quantity: 2,
    price: 263,
    originalPrice: 350,
    discount: 25,
    status: "placed",
    deliveryInfo: "Delivery expected by Sat Dec 13",
    statusMessage: "Your Order has been placed and is being processed",
    orderDate: "2024-12-07",
    estimatedDelivery: "2024-12-13",
    orderNumber: "ORD-7843",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop",
    category: "Home & Living",
    brand: "Home Essentials",
    rating: 4.5,
    reviews: 89,
    deliveryMethod: "Standard",
  },
  {
    id: 3,
    productName: "Premium Cotton Oversized T-Shirt",
    description: "100% organic cotton t-shirt with premium finish and oversized fit",
    color: "White, Black",
    size: "L",
    quantity: 3,
    price: 299,
    originalPrice: 399,
    discount: 25,
    status: "delivered",
    deliveryInfo: "Delivered on Dec 5",
    statusMessage: "Your item has been delivered successfully",
    orderDate: "2024-12-01",
    deliveredDate: "2024-12-05",
    orderNumber: "ORD-7840",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop",
    category: "Fashion",
    brand: "Minimalist Wear",
    rating: 4.7,
    reviews: 256,
    deliveryMethod: "Express",
    trackingNumber: "TRK78401547",
  },
  {
    id: 4,
    productName: "Noise Cancellation Wireless Headphones",
    description: "Premium wireless headphones with active noise cancellation and 30hr battery life",
    color: "Matte Black",
    size: null,
    quantity: 1,
    price: 899,
    originalPrice: 1299,
    discount: 31,
    status: "shipped",
    deliveryInfo: "Arriving by Dec 10",
    statusMessage: "Shipped via Express Delivery",
    orderDate: "2024-12-06",
    estimatedDelivery: "2024-12-10",
    orderNumber: "ORD-7841",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    category: "Electronics",
    brand: "SoundBeats",
    rating: 4.8,
    reviews: 534,
    deliveryMethod: "Express",
    trackingNumber: "TRK78418932",
  },
  {
    id: 5,
    productName: "Genuine Leather Bi-fold Wallet",
    description: "Handcrafted genuine leather wallet with RFID protection and 12 card slots",
    color: "Cognac Brown",
    size: null,
    quantity: 1,
    price: 199,
    originalPrice: 299,
    discount: 33,
    status: "placed",
    deliveryInfo: "Expected by Dec 15",
    statusMessage: "Processing your order - ETA 3-5 business days",
    orderDate: "2024-12-07",
    estimatedDelivery: "2024-12-15",
    orderNumber: "ORD-7844",
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=400&h=400&fit=crop",
    category: "Accessories",
    brand: "LeatherCraft",
    rating: 4.6,
    reviews: 187,
    deliveryMethod: "Standard",
  },
  {
    id: 6,
    productName: "Smart Watch Series 5 Pro",
    description: "Advanced smartwatch with ECG, blood oxygen monitoring, and fitness tracking",
    color: "Midnight Black",
    size: "44mm",
    quantity: 1,
    price: 1299,
    originalPrice: 1599,
    discount: 19,
    status: "delivered",
    deliveryInfo: "Delivered on Dec 3",
    statusMessage: "Successfully delivered and signed for",
    orderDate: "2024-11-28",
    deliveredDate: "2024-12-03",
    orderNumber: "ORD-7839",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
    category: "Electronics",
    brand: "TechWear",
    rating: 4.9,
    reviews: 892,
    deliveryMethod: "Express",
    trackingNumber: "TRK78394561",
  },
  {
    id: 7,
    productName: "Organic Bamboo Bed Sheet Set",
    description: "Luxury 1000 thread count bamboo bed sheets with temperature regulation",
    color: "Sage Green",
    size: "King",
    quantity: 1,
    price: 349,
    originalPrice: 499,
    discount: 30,
    status: "cancelled",
    deliveryInfo: "Order was cancelled",
    statusMessage: "Order cancelled by customer",
    orderDate: "2024-11-25",
    cancelledDate: "2024-11-26",
    orderNumber: "ORD-7838",
    image: "https://images.unsplash.com/photo-1556228578-9c360e2d0b4a?w=400&h=400&fit=crop",
    category: "Home & Living",
    brand: "SleepWell",
    rating: 4.4,
    reviews: 312,
    deliveryMethod: "Standard",
  },
  {
    id: 8,
    productName: "Wireless Earbuds Pro",
    description: "True wireless earbuds with spatial audio and water resistance",
    color: "White",
    size: null,
    quantity: 2,
    price: 599,
    originalPrice: 799,
    discount: 25,
    status: "returned",
    deliveryInfo: "Return processed",
    statusMessage: "Return completed - refund initiated",
    orderDate: "2024-11-20",
    returnedDate: "2024-11-28",
    orderNumber: "ORD-7837",
    image: "https://images.unsplash.com/photo-1590658165737-15a047b8b5e9?w=400&h=400&fit=crop",
    category: "Electronics",
    brand: "AudioPro",
    rating: 4.3,
    reviews: 421,
    deliveryMethod: "Express",
  },
  {
    id: 9,
    productName: "Yoga Mat Premium Edition",
    description: "Eco-friendly non-slip yoga mat with alignment markers and carrying strap",
    color: "Ocean Blue",
    size: "72x24 inches",
    quantity: 1,
    price: 149,
    originalPrice: 199,
    discount: 25,
    status: "delivered",
    deliveryInfo: "Delivered on Nov 30",
    statusMessage: "Delivered - Left at front door",
    orderDate: "2024-11-18",
    deliveredDate: "2024-11-30",
    orderNumber: "ORD-7836",
    image: "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=400&h=400&fit=crop",
    category: "Fitness",
    brand: "FlexiMat",
    rating: 4.8,
    reviews: 567,
    deliveryMethod: "Standard",
    trackingNumber: "TRK78367890",
  },
  {
    id: 10,
    productName: "Ceramic Coffee Mug Set",
    description: "Set of 4 handmade ceramic mugs with ergonomic handle design",
    color: "Terracotta",
    size: "400ml each",
    quantity: 1,
    price: 89,
    originalPrice: 129,
    discount: 31,
    status: "shipped",
    deliveryInfo: "Arriving by Dec 9",
    statusMessage: "Package in transit - last scanned at distribution center",
    orderDate: "2024-12-05",
    estimatedDelivery: "2024-12-09",
    orderNumber: "ORD-7845",
    image: "https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?w=400&h=400&fit=crop",
    category: "Home & Living",
    brand: "Artisan Pottery",
    rating: 4.7,
    reviews: 234,
    deliveryMethod: "Standard",
    trackingNumber: "TRK78452341",
  },
  {
    id: 11,
    productName: "Gaming Laptop Pro",
    description: "High-performance gaming laptop with RTX 4070 and 32GB RAM",
    color: "Lunar Gray",
    size: "17.3 inch",
    quantity: 1,
    price: 2199,
    originalPrice: 2799,
    discount: 21,
    status: "placed",
    deliveryInfo: "Expected by Dec 20",
    statusMessage: "Order confirmed - preparing for shipment",
    orderDate: "2024-12-06",
    estimatedDelivery: "2024-12-20",
    orderNumber: "ORD-7846",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400&h=400&fit=crop",
    category: "Electronics",
    brand: "GameMaster",
    rating: 4.9,
    reviews: 1123,
    deliveryMethod: "Express",
  },
  {
    id: 12,
    productName: "Running Shoes Air Max",
    description: "Lightweight running shoes with air cushioning and breathable mesh",
    color: "Neon Green/Black",
    size: "US 10",
    quantity: 1,
    price: 399,
    originalPrice: 499,
    discount: 20,
    status: "delivered",
    deliveryInfo: "Delivered on Dec 2",
    statusMessage: "Delivered successfully",
    orderDate: "2024-11-29",
    deliveredDate: "2024-12-02",
    orderNumber: "ORD-7835",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    category: "Fashion",
    brand: "RunFast",
    rating: 4.6,
    reviews: 678,
    deliveryMethod: "Express",
    trackingNumber: "TRK78351234",
  },
];

    return (
        <StoreLayout>
            
 <OrderHistory order={dummyOrders} />
          
           
        </StoreLayout>
    )
};

export default OrdersPage;